// Generated by gencpp from file move_demo/CamToRealResponse.msg
// DO NOT EDIT!


#ifndef MOVE_DEMO_MESSAGE_CAMTOREALRESPONSE_H
#define MOVE_DEMO_MESSAGE_CAMTOREALRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_demo
{
template <class ContainerAllocator>
struct CamToRealResponse_
{
  typedef CamToRealResponse_<ContainerAllocator> Type;

  CamToRealResponse_()
    : obj_x(0.0)
    , obj_y(0.0)
    , obj_z(0.0)
    , result(false)  {
    }
  CamToRealResponse_(const ContainerAllocator& _alloc)
    : obj_x(0.0)
    , obj_y(0.0)
    , obj_z(0.0)
    , result(false)  {
  (void)_alloc;
    }



   typedef double _obj_x_type;
  _obj_x_type obj_x;

   typedef double _obj_y_type;
  _obj_y_type obj_y;

   typedef double _obj_z_type;
  _obj_z_type obj_z;

   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::move_demo::CamToRealResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_demo::CamToRealResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CamToRealResponse_

typedef ::move_demo::CamToRealResponse_<std::allocator<void> > CamToRealResponse;

typedef boost::shared_ptr< ::move_demo::CamToRealResponse > CamToRealResponsePtr;
typedef boost::shared_ptr< ::move_demo::CamToRealResponse const> CamToRealResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_demo::CamToRealResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_demo::CamToRealResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_demo::CamToRealResponse_<ContainerAllocator1> & lhs, const ::move_demo::CamToRealResponse_<ContainerAllocator2> & rhs)
{
  return lhs.obj_x == rhs.obj_x &&
    lhs.obj_y == rhs.obj_y &&
    lhs.obj_z == rhs.obj_z &&
    lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_demo::CamToRealResponse_<ContainerAllocator1> & lhs, const ::move_demo::CamToRealResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::move_demo::CamToRealResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_demo::CamToRealResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_demo::CamToRealResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_demo::CamToRealResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_demo::CamToRealResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_demo::CamToRealResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_demo::CamToRealResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8a34a4411ad0412a5ef662d2317a130";
  }

  static const char* value(const ::move_demo::CamToRealResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8a34a4411ad0412ULL;
  static const uint64_t static_value2 = 0xa5ef662d2317a130ULL;
};

template<class ContainerAllocator>
struct DataType< ::move_demo::CamToRealResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_demo/CamToRealResponse";
  }

  static const char* value(const ::move_demo::CamToRealResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_demo::CamToRealResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 obj_x\n"
"float64 obj_y\n"
"float64 obj_z\n"
"bool result\n"
"\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::move_demo::CamToRealResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_demo::CamToRealResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obj_x);
      stream.next(m.obj_y);
      stream.next(m.obj_z);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CamToRealResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_demo::CamToRealResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_demo::CamToRealResponse_<ContainerAllocator>& v)
  {
    s << indent << "obj_x: ";
    Printer<double>::stream(s, indent + "  ", v.obj_x);
    s << indent << "obj_y: ";
    Printer<double>::stream(s, indent + "  ", v.obj_y);
    s << indent << "obj_z: ";
    Printer<double>::stream(s, indent + "  ", v.obj_z);
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_DEMO_MESSAGE_CAMTOREALRESPONSE_H
