// Generated by gencpp from file move_demo/CamToReal.msg
// DO NOT EDIT!


#ifndef MOVE_DEMO_MESSAGE_CAMTOREAL_H
#define MOVE_DEMO_MESSAGE_CAMTOREAL_H

#include <ros/service_traits.h>


#include <move_demo/CamToRealRequest.h>
#include <move_demo/CamToRealResponse.h>


namespace move_demo
{

struct CamToReal
{

typedef CamToRealRequest Request;
typedef CamToRealResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CamToReal
} // namespace move_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_demo::CamToReal > {
  static const char* value()
  {
    return "189ac79be7b27a6947e618b03843336a";
  }

  static const char* value(const ::move_demo::CamToReal&) { return value(); }
};

template<>
struct DataType< ::move_demo::CamToReal > {
  static const char* value()
  {
    return "move_demo/CamToReal";
  }

  static const char* value(const ::move_demo::CamToReal&) { return value(); }
};


// service_traits::MD5Sum< ::move_demo::CamToRealRequest> should match
// service_traits::MD5Sum< ::move_demo::CamToReal >
template<>
struct MD5Sum< ::move_demo::CamToRealRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_demo::CamToReal >::value();
  }
  static const char* value(const ::move_demo::CamToRealRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_demo::CamToRealRequest> should match
// service_traits::DataType< ::move_demo::CamToReal >
template<>
struct DataType< ::move_demo::CamToRealRequest>
{
  static const char* value()
  {
    return DataType< ::move_demo::CamToReal >::value();
  }
  static const char* value(const ::move_demo::CamToRealRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_demo::CamToRealResponse> should match
// service_traits::MD5Sum< ::move_demo::CamToReal >
template<>
struct MD5Sum< ::move_demo::CamToRealResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_demo::CamToReal >::value();
  }
  static const char* value(const ::move_demo::CamToRealResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_demo::CamToRealResponse> should match
// service_traits::DataType< ::move_demo::CamToReal >
template<>
struct DataType< ::move_demo::CamToRealResponse>
{
  static const char* value()
  {
    return DataType< ::move_demo::CamToReal >::value();
  }
  static const char* value(const ::move_demo::CamToRealResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_DEMO_MESSAGE_CAMTOREAL_H
