// Generated by gencpp from file move_demo/FindNearestModelResponse.msg
// DO NOT EDIT!


#ifndef MOVE_DEMO_MESSAGE_FINDNEARESTMODELRESPONSE_H
#define MOVE_DEMO_MESSAGE_FINDNEARESTMODELRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_demo
{
template <class ContainerAllocator>
struct FindNearestModelResponse_
{
  typedef FindNearestModelResponse_<ContainerAllocator> Type;

  FindNearestModelResponse_()
    : model_name()  {
    }
  FindNearestModelResponse_(const ContainerAllocator& _alloc)
    : model_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _model_name_type;
  _model_name_type model_name;





  typedef boost::shared_ptr< ::move_demo::FindNearestModelResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_demo::FindNearestModelResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FindNearestModelResponse_

typedef ::move_demo::FindNearestModelResponse_<std::allocator<void> > FindNearestModelResponse;

typedef boost::shared_ptr< ::move_demo::FindNearestModelResponse > FindNearestModelResponsePtr;
typedef boost::shared_ptr< ::move_demo::FindNearestModelResponse const> FindNearestModelResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_demo::FindNearestModelResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_demo::FindNearestModelResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_demo::FindNearestModelResponse_<ContainerAllocator1> & lhs, const ::move_demo::FindNearestModelResponse_<ContainerAllocator2> & rhs)
{
  return lhs.model_name == rhs.model_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_demo::FindNearestModelResponse_<ContainerAllocator1> & lhs, const ::move_demo::FindNearestModelResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::move_demo::FindNearestModelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_demo::FindNearestModelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_demo::FindNearestModelResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_demo::FindNearestModelResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_demo::FindNearestModelResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_demo::FindNearestModelResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_demo::FindNearestModelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea31c8eab6fc401383cf528a7c0984ba";
  }

  static const char* value(const ::move_demo::FindNearestModelResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea31c8eab6fc4013ULL;
  static const uint64_t static_value2 = 0x83cf528a7c0984baULL;
};

template<class ContainerAllocator>
struct DataType< ::move_demo::FindNearestModelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_demo/FindNearestModelResponse";
  }

  static const char* value(const ::move_demo::FindNearestModelResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_demo::FindNearestModelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string model_name\n"
;
  }

  static const char* value(const ::move_demo::FindNearestModelResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_demo::FindNearestModelResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.model_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindNearestModelResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_demo::FindNearestModelResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_demo::FindNearestModelResponse_<ContainerAllocator>& v)
  {
    s << indent << "model_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.model_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_DEMO_MESSAGE_FINDNEARESTMODELRESPONSE_H
