// Generated by gencpp from file move_demo/FindNearestModelRequest.msg
// DO NOT EDIT!


#ifndef MOVE_DEMO_MESSAGE_FINDNEARESTMODELREQUEST_H
#define MOVE_DEMO_MESSAGE_FINDNEARESTMODELREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_demo
{
template <class ContainerAllocator>
struct FindNearestModelRequest_
{
  typedef FindNearestModelRequest_<ContainerAllocator> Type;

  FindNearestModelRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  FindNearestModelRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::move_demo::FindNearestModelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_demo::FindNearestModelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FindNearestModelRequest_

typedef ::move_demo::FindNearestModelRequest_<std::allocator<void> > FindNearestModelRequest;

typedef boost::shared_ptr< ::move_demo::FindNearestModelRequest > FindNearestModelRequestPtr;
typedef boost::shared_ptr< ::move_demo::FindNearestModelRequest const> FindNearestModelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_demo::FindNearestModelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_demo::FindNearestModelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_demo::FindNearestModelRequest_<ContainerAllocator1> & lhs, const ::move_demo::FindNearestModelRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_demo::FindNearestModelRequest_<ContainerAllocator1> & lhs, const ::move_demo::FindNearestModelRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::move_demo::FindNearestModelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_demo::FindNearestModelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_demo::FindNearestModelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_demo::FindNearestModelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_demo::FindNearestModelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_demo::FindNearestModelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_demo::FindNearestModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::move_demo::FindNearestModelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::move_demo::FindNearestModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_demo/FindNearestModelRequest";
  }

  static const char* value(const ::move_demo::FindNearestModelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_demo::FindNearestModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# FindNearestModel.srv\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::move_demo::FindNearestModelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_demo::FindNearestModelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindNearestModelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_demo::FindNearestModelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_demo::FindNearestModelRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_DEMO_MESSAGE_FINDNEARESTMODELREQUEST_H
