// Generated by gencpp from file move_demo/FindNearestModel.msg
// DO NOT EDIT!


#ifndef MOVE_DEMO_MESSAGE_FINDNEARESTMODEL_H
#define MOVE_DEMO_MESSAGE_FINDNEARESTMODEL_H

#include <ros/service_traits.h>


#include <move_demo/FindNearestModelRequest.h>
#include <move_demo/FindNearestModelResponse.h>


namespace move_demo
{

struct FindNearestModel
{

typedef FindNearestModelRequest Request;
typedef FindNearestModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FindNearestModel
} // namespace move_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_demo::FindNearestModel > {
  static const char* value()
  {
    return "cd680775ebeed150a97dc7d17020a53d";
  }

  static const char* value(const ::move_demo::FindNearestModel&) { return value(); }
};

template<>
struct DataType< ::move_demo::FindNearestModel > {
  static const char* value()
  {
    return "move_demo/FindNearestModel";
  }

  static const char* value(const ::move_demo::FindNearestModel&) { return value(); }
};


// service_traits::MD5Sum< ::move_demo::FindNearestModelRequest> should match
// service_traits::MD5Sum< ::move_demo::FindNearestModel >
template<>
struct MD5Sum< ::move_demo::FindNearestModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_demo::FindNearestModel >::value();
  }
  static const char* value(const ::move_demo::FindNearestModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_demo::FindNearestModelRequest> should match
// service_traits::DataType< ::move_demo::FindNearestModel >
template<>
struct DataType< ::move_demo::FindNearestModelRequest>
{
  static const char* value()
  {
    return DataType< ::move_demo::FindNearestModel >::value();
  }
  static const char* value(const ::move_demo::FindNearestModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_demo::FindNearestModelResponse> should match
// service_traits::MD5Sum< ::move_demo::FindNearestModel >
template<>
struct MD5Sum< ::move_demo::FindNearestModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_demo::FindNearestModel >::value();
  }
  static const char* value(const ::move_demo::FindNearestModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_demo::FindNearestModelResponse> should match
// service_traits::DataType< ::move_demo::FindNearestModel >
template<>
struct DataType< ::move_demo::FindNearestModelResponse>
{
  static const char* value()
  {
    return DataType< ::move_demo::FindNearestModel >::value();
  }
  static const char* value(const ::move_demo::FindNearestModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_DEMO_MESSAGE_FINDNEARESTMODEL_H
