// Generated by gencpp from file move_demo/TrackObj.msg
// DO NOT EDIT!


#ifndef MOVE_DEMO_MESSAGE_TRACKOBJ_H
#define MOVE_DEMO_MESSAGE_TRACKOBJ_H

#include <ros/service_traits.h>


#include <move_demo/TrackObjRequest.h>
#include <move_demo/TrackObjResponse.h>


namespace move_demo
{

struct TrackObj
{

typedef TrackObjRequest Request;
typedef TrackObjResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TrackObj
} // namespace move_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_demo::TrackObj > {
  static const char* value()
  {
    return "d6d04e8b2c20037b11fd9c862b657664";
  }

  static const char* value(const ::move_demo::TrackObj&) { return value(); }
};

template<>
struct DataType< ::move_demo::TrackObj > {
  static const char* value()
  {
    return "move_demo/TrackObj";
  }

  static const char* value(const ::move_demo::TrackObj&) { return value(); }
};


// service_traits::MD5Sum< ::move_demo::TrackObjRequest> should match
// service_traits::MD5Sum< ::move_demo::TrackObj >
template<>
struct MD5Sum< ::move_demo::TrackObjRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_demo::TrackObj >::value();
  }
  static const char* value(const ::move_demo::TrackObjRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_demo::TrackObjRequest> should match
// service_traits::DataType< ::move_demo::TrackObj >
template<>
struct DataType< ::move_demo::TrackObjRequest>
{
  static const char* value()
  {
    return DataType< ::move_demo::TrackObj >::value();
  }
  static const char* value(const ::move_demo::TrackObjRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_demo::TrackObjResponse> should match
// service_traits::MD5Sum< ::move_demo::TrackObj >
template<>
struct MD5Sum< ::move_demo::TrackObjResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_demo::TrackObj >::value();
  }
  static const char* value(const ::move_demo::TrackObjResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_demo::TrackObjResponse> should match
// service_traits::DataType< ::move_demo::TrackObj >
template<>
struct DataType< ::move_demo::TrackObjResponse>
{
  static const char* value()
  {
    return DataType< ::move_demo::TrackObj >::value();
  }
  static const char* value(const ::move_demo::TrackObjResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_DEMO_MESSAGE_TRACKOBJ_H
