// Generated by gencpp from file move_demo/TrackObjRequest.msg
// DO NOT EDIT!


#ifndef MOVE_DEMO_MESSAGE_TRACKOBJREQUEST_H
#define MOVE_DEMO_MESSAGE_TRACKOBJREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_demo
{
template <class ContainerAllocator>
struct TrackObjRequest_
{
  typedef TrackObjRequest_<ContainerAllocator> Type;

  TrackObjRequest_()
    : obj()  {
    }
  TrackObjRequest_(const ContainerAllocator& _alloc)
    : obj(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _obj_type;
  _obj_type obj;





  typedef boost::shared_ptr< ::move_demo::TrackObjRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_demo::TrackObjRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TrackObjRequest_

typedef ::move_demo::TrackObjRequest_<std::allocator<void> > TrackObjRequest;

typedef boost::shared_ptr< ::move_demo::TrackObjRequest > TrackObjRequestPtr;
typedef boost::shared_ptr< ::move_demo::TrackObjRequest const> TrackObjRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_demo::TrackObjRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_demo::TrackObjRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_demo::TrackObjRequest_<ContainerAllocator1> & lhs, const ::move_demo::TrackObjRequest_<ContainerAllocator2> & rhs)
{
  return lhs.obj == rhs.obj;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_demo::TrackObjRequest_<ContainerAllocator1> & lhs, const ::move_demo::TrackObjRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::move_demo::TrackObjRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_demo::TrackObjRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_demo::TrackObjRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_demo::TrackObjRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_demo::TrackObjRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_demo::TrackObjRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_demo::TrackObjRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8fd46ff9e0d150d043714f673d35559";
  }

  static const char* value(const ::move_demo::TrackObjRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8fd46ff9e0d150dULL;
  static const uint64_t static_value2 = 0x043714f673d35559ULL;
};

template<class ContainerAllocator>
struct DataType< ::move_demo::TrackObjRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_demo/TrackObjRequest";
  }

  static const char* value(const ::move_demo::TrackObjRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_demo::TrackObjRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string obj\n"
;
  }

  static const char* value(const ::move_demo::TrackObjRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_demo::TrackObjRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obj);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackObjRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_demo::TrackObjRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_demo::TrackObjRequest_<ContainerAllocator>& v)
  {
    s << indent << "obj: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.obj);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_DEMO_MESSAGE_TRACKOBJREQUEST_H
